apiVersion: v1
kind: Service
metadata:
  name: example-app-svc
spec:
  type: NodePort
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
