apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: argocd-demo
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/CalebReigada/argocd-demo.git
    targetRevision: HEAD
    path: example-app

  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp
  
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true

    automated: 
      selfHeal: true
      prune: true

